---
name: Build
on:
  push:
    branches:
      - master
permissions: read-all
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.15
      - name: Validate JSON files
        run: >
          find . -name "*.json" | xargs -L1 bunx jsonlint@1.6.3 --quiet --compact
  builder:
    name: Builder
    runs-on: self-hosted
    strategy:
      matrix:
        game:
          - valheim
      fail-fast: false
      max-parallel: 1
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup jq
        uses: dcarbone/install-jq-action@v2
        with:
          version: "1.7"
          force: false
      - id: depot
        run: >
          echo "steamAppId=$(cat depots.json | jq -rcM '.${{ matrix.game }}.steamAppId' | tr -d '\n\r')" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.depot.steamAppId }}"
